# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "29. Heidelberger Symposium"
email: "info@hcwk.de"
description: "Studentisch organisierte Plattform zum interdisziplinären Austausch"
baseurl: ""
url: "https://heidelberger-symposium.de"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-87159276-1"
googleAnalyticsSiteUrl: "heidelberger-symposium.de"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "HCWK"
organizerAlternateName: "Heidelberger Club für Wirtschaft und Kultur e.V."
organizerDescription: "Studentisch organisierter, gemeinnütziger Verein zur Förderung von Bildung"
organizerEmail: "vorstand@hcwk.de"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://hcwk.de/"

# Head
metaKeywords: "conference, heidelberg, event, symposium, wissenschaft, bildung,"
twitterAccount: "@HCWK"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "#"
c4sponsorsUrl: "#"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Programm"}
 - {permalink: "/speakers/", text: "Referenten"}
 - {permalink: "/team/", text: "Veranstalter"}
 - {permalink: "/logistics/", text: "Logistik"}
# - {permalink: "/hackathon/", text: "Hackathon"}
#bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "29. Heidelberger Symposium </br> <typeout>"
eventDate: "11. Mai - 13. Mai, 2017"
typeoutTextValues: '"", "Kunst", "Kultur", "Politik", "Gesellschaft", "Wissenschaft"'
typeoutFallback: ""
heroButtons:
# - {link: "#", text: "Nimm teil."}
 - {permalink: "/#tickets", text: "Kaufe Tickets"}

# About Block
aboutTitle: "Über das Heidelberger Symposium"
aboutBlock:
 - {title: "Podiumsdiskussionen", image: "podium.jpg", text: "Gesprächsrunden mit ausgewählten Diskutanten" }
 - {title: "Vorträge", image: "vortrag.jpg", text: "Vorträge von herausragenden Menschen" }
 - {title: "Kolloquinen", image: "kolloquium.jpg", text: "Nachfragen ausdrücklich erwünscht" }
 - {title: "Workshop", image: "workshop.jpg", text: "Hands-on in kleinen Gruppen" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1000", specialCharacter: "±", info: "Teilnehmer", detail: "aus der Region"}
 - {count: "60", specialCharacter: "+", info: "Stunden", detail: "Kunst, Kultur, Politik, Gesellschaft und Wissenschaft"}
 - {count: "40", specialCharacter: "+", info: "Referenten", detail: "aus dem In- und Ausland"}
 - {count: "3", specialCharacter: "", info: "Tage", detail: "Getränke, Frühstück und Mittagessen im Festzelt"}

# Latest News Block
latestNewsTitle: "Neuigkeiten"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 5
rockstarSpeakersTitle: "Rockstar Referenten"
rockstarSpeakersButtonText: "Alle Referenten"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Neue Universität"
#eventLocationLink: "#"
eventStreetAddress: "Universitätsplatz"
eventAddressLocality: "Heidelberg"
eventAddressLocalityRegion: "Baden-Württemberg"
eventPostalCode: "69117"
eventAddressCountry: "Deutschland"
eventStartTime: "2017-05-11T09:00"
eventDoorTime: "09:00"
eventEndTime: "2017-05-13T18:00"
eventPlaceCoordinates: "49.410735, 8.706508"
mapCenterCoordinates: "49.410735, 8.704028"
mapMobileCenterCoordinates: "49.410735, 8.706508"

# Venue Block
venueBlockTitle: "Veranstaltungsort"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Neue Universität, Heidelberg"
venueFeatures: ["Aula", "Hörsaal 13", "Hörsaal 14"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "hdsymposium"
twitterFeed: "#"

# Partners Block
#organizersTitle: "Organizers"
partnersTitle: "Sponsoren"
partnersC4sponsorsButton: "Werden Sie Sponsor"

# # Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "Ein Ticket berechtigt den Zugang zu allen Veranstaltungen sowie Speisen und Getränke im Festzelt"
ticketsOffers:
 -
  name: "Normal"
  price: "30"
  priceCurrency: "EUR"
  #ticketsNumber: "50"
  buyButtonLink: "#"
  buyButtonText: "Kaufen"
  featured: true
#  additionalInfo: "Nur in Verbindung mit gültigem Schüler-, Studenten-, oder Renternausweis."
  ticketContentList: ["Zugang zu allen Veranstaltungen 🤓", "Bewirtung im Zelt 🍴 🍺", "Eintritt zur After Party 🎉"]
  validFrom: "2017-03-11T10:00"
  validThrough: "2017-05-13T23:59"
 -
  name: "Reduziert"
  price: "17"
  priceCurrency: "EUR"
  #ticketsNumber: "50"
  buyButtonLink: "#"
  buyButtonText: "Kaufen"
  featured: true
  additionalInfo: "Nur in Verbindung mit gültigem Schüler-, Studenten-, oder Renternausweis"
  ticketContentList: ["Zugang zu allen Veranstaltungen 🤓", "Bewirtung im Zelt 🍴 🍺", "Eintritt zur After Party 🎉", "Nur in Verbindung mit gültigem Schüler-, Studenten-, oder Renternausweis" ]
  validFrom: "2017-03-11T10:00"
  validThrough: "2017-05-13T23:59"

# Footer
socialLinks:
 - {link: "https://twitter.com/hcwk", icon: "twitter"}
 - {link: "https://facebook.com/heidelbergersymposium/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}

footerBlocks:
-
  title: "Social"
  links:
   - {link: "https://facebook.com/heidelbergersymposium/", text: "facebook"}
   - {link: "https://twitter.com/hcwk", text: "twitter"}
   - {link: "https://www.instagram.com/symposium_hd/", text: "instagram"}
-
  title: "Kontakt"
  links:
   - {link: "mailto:info@hcwk.de", text: "info@hcwk.de"}
   - {link: "tel:+496221707190", text: "Tel: +49 (0)6221 70 71 90"}
   - {link: "fax:+496221707219", text: "Fax: +49 (0)6221 70 72 19"}
-
  title: "Adresse"
  texts:
   - {text: "Heidelberger Club für Wirtschaft und Kultur e.V."}
   - {text: "Luisenstraße 3"}
   - {text: "69117 Heidelberg"}
-
  title: "Legal"
  links:
  # - {permalink: "/cod/", text: "Code of Conduct"}
   - {permalink: "/impressum/", text: "Impressum"}
   - {permalink: "/datenschutz/", text: "Datenschutz"}
# Blog
blogTitle: "Neuigkeiten"
blogCommentsEnabled: true
discusShortName: "hdsymposium"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "Über uns"
aboutUs: "<p>Der Heidelberger Club für Wirtschaft und Kultur e. V. (HCWK) ist eine unabhängige, überparteiliche und fachübergreifende Studenteninitiative, die 1988 mit dem Ziel gegründet wurde, die Ausbildung an den Universitäten durch Praxisbezug und interdisziplinären Austausch zu ergänzen. Zu diesem Zweck organisiert der Club jährlich ein mehrtägiges Forum zu einem aktuellen Thema von gesellschaftlicher Relevanz. </p>

<p>In seinem 28-jährigen Bestehen hat sich das Symposium zu einem festen Bestandteil des akademischen Lebens der Stadt Heidelberg etabliert und leistet damit einen bedeutenden Beitrag zu einer lebendigen Universitätskultur.</p>

<h6>Kultur und Wirtschaft – ein Paradoxon?</h6>

<p>Unser Ziel ist es, diese beiden Begriffe in einen Dialog treten zu lassen. Es soll ein interdisziplinäres Forum für lebendige und kontroverse Debatten geschaffen werden, um Diskussionskultur zu pflegen und dem Bildungsideal vom ganzheitlichen Menschen näher zu kommen. Querdenken wird hier nicht als etwas Karrierehemmendes unterdrückt, sondern als konstruktiver Impuls geschätzt.</p>

<p>Die Umsetzung des Symposiums ermöglicht es jedem Studenten, sein theoretisches Wissen mit einem Praxisbezug zu verbinden. Dabei ist die effektive Zusammenarbeit mit dem Team Voraussetzung und Herausforderung zugleich. Die Vorbereitung einer solchen Großveranstaltung beansprucht die beteiligten Organisatoren über ein ganzes Jahr und bindet sie zeitlich neben dem Studium erheblich ein. Die anfallenden Aufgaben decken ein breites Spektrum an verschiedensten Tätigkeiten und Einsatzgebieten ab, so dass jedes Mitglied ein auf die eigenen Interessen und Fähigkeiten abgestimmtes Aufgabenprofil finden kann: von der Programmkonzeption über PR-Arbeit und Spendenakquise, Referentenanwerbung und –betreuung, bis hin zum Zeltaufbau und der Durchführung der dreitägigen Veranstaltung im Konkreten. Mag die Mitarbeit für manchen Beteiligten durchaus eine Belastungsprobe sein, so ist bisher aber wohl noch jeder durch das Ergebnis entschädigt worden: nicht nur entlohnt das Gefühl, etwas Großartiges auf die Beine gestellt zu haben, es werden auch neue Freundschaften geknüpft, Fähigkeiten gestärkt, Neugier gestillt und Wissen erweitert.</p>

<p>Als anerkannter allgemeinnütziger Verein wird seine Tätigkeit durch Spenden, den Verzicht der Referenten auf Honorare sowie das ehrenamtliche Engagement der Organisatoren getragen. Sowohl Förderer aus der Wirtschaft und dem Stiftungswesen als auch ein hochkarätig besetztes Kuratorium unterstützen den Club finanziell und ideell. Für sein Engagement wurde der HCWK von der Initiative „Deutschland – Land der Ideen“ als ein „Ausgewählter Ort 2008“ ausgezeichnet und mit dem Heidelberger Symposium 2010 in das Programm „Jugend in Aktion“ der Europäischen Union aufgenommen. Neben der Organisation der Symposien wurden über die Jahre zwei weitere Veranstaltungen entwickelt und inzwischen auch beide mehrfach durchgeführt: die Ausschreibung und Verleihung des Heidelberger Kunst- und Kulturpreises und die Durchführung des Heidelberger Berufsinformationstages.</p>"

# Logistics Find Way Block
findWayTitle: ""
findWayDistance: "Distanz"
findWayDriving: "Auto"
findWayWalking: "zu Fuß"
findWayBicycling: "mit dem Rad"
findWayTransit: "ÖPV"
#findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.410688, 8.222069"
logisticsMapMobileCenterCoordinates: "49.410688, 8.222069"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "In Heidelberg"
directionDetailsCards:
 - {title: "Vom Hauptbahnhof", information: 'Der Heidelberger Hauptbahnhof befindet sich im Westen der Stadt. Mit der Buslinie 32 gelangen Sie direkt zum Universitätsplatz. <a href="https://www.vrn.de/mng/#/XSLT_TRIP_REQUEST2?restriction=0&orig=Heidelberg, Hauptbahnhof&dest=Heidelberg, Universitätsplatz&isDeparture=true" target="_blank">Auskunft des VRN</a>.'}
 - {title: "ÖPNV", information: 'Der VRN bedient mit den Buslinien 32 und 31 die <a href="https://www.vrn.de/mng/#/XSLT_TRIP_REQUEST2?restriction=0&dest=Heidelberg, Universitätsplatz&isDeparture=true" target="_blank">Haltestelle <i>Universitätsplatz</i> </a>'}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
